[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm rebuild better-sqlite3"]

[start]
cmd = "cd server && node index.js"
