[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd server && npm install --production"]

[phases.build]
cmds = ["echo 'No build needed for server'"]

[start]
cmd = "cd server && node index.js"
